# Generated by Django 2.2.5 on 2019-09-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_photo', models.URLField()),
                ('link', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
